### PR TITLE
[AT][ABC][Submenu]DefaultStateOfABCPage_AfterNavigatingOnPage<IrynaDanilevska>

### PR DESCRIPTION
**Pull request by IrynaDanilevska**
testDefaultStateOfABCPage_AfterNavigatingOnPage_HappyPath()
[US] - https://trello.com/c/ST9avavI/182-usfunctionalabcsubmenu-search-for-language-by-letter-or-number-name 
[AT] -https://trello.com/c/omaYLTbE/284-atabcsubmenu-testdefaultstateofabcpageafternavigatingonpagehappypathirynadanilevska

### CODE REVIEW

**Comment by IrynaDanilevska** [comment]
[[AT][ABC][submenu] testDefaultStateOfABCPage_AfterNavigatingOnPage_HappyPath<IrynaDanilevska>](https://trello.com/c/omaYLTbE/284-atabcsubmenu-testdefaultstateofabcpageafternavigatingonpagehappypathirynadanilevska)

**Review by Vira05 — APPROVED** [review]

**Comment by Vira05** [comment]
Please add the card TC from Trello to PR

**Comment by Vira05** [comment]
Yes, you right. I've just saw you have 3 cards in Trello

**Review by yuriiormson — APPROVED** [review]

**Review by achytyd — APPROVED** [review]

**Comment by achytyd** [comment]
@IrynaDanilevska could you review my PR and approve it if it looks ok? https://github.com/RedRoverSchool/AutomationQA_05/pull/71

**Pull request merged**
