### PR TITLE
[AT][Functional][Search][form] testSearchForLanguageByName_HappyPath() <AnaLara>

### PR DESCRIPTION
**Pull request by Ana-Lara**
testSearchLanguageField_HappyPath added

[US] https://trello.com/c/Pfi21TZq/49-usfunctionalsearchform-search-for-language-feild
[TC] https://trello.com/c/NSs9ExK4/255-tcsearchform-verify-if-user-is-searching-for-programming-language-by-name-and-can-see-the-list-of-relative-results-analara
[AT] https://trello.com/c/z0h5ZbRP/257-atsearchform-testsearchforlanguagebynamehappypath-analara

### CODE REVIEW

**Review by verafes — APPROVED** [review]

**Review by ArinaJur — CHANGES_REQUESTED** [review]
Назовите ваш PR согласно правилам, пожалуйста. Посмотрите, как названы другие PRs

**Comment by Ana-Lara** [comment]
> Назовите ваш PR согласно правилам, пожалуйста. Посмотрите, как названы другие PRs

Done. I've updated the name of my PR. Could you, please, approve it so that I could merge it? Thank you!

**Comment by ArinaJur** [comment]
The nick name on Trello card is not the same as nick name on PR. Also please provide labels. And please change "PR name" on card to test name
Screenshot_20221115_014613_Chrome

**Comment by Ana-Lara** [comment]
[[AT][Search][form] testSearchForLanguageByName_HappyPath() <AnaLara>](https://trello.com/c/z0h5ZbRP/257-atsearchform-testsearchforlanguagebynamehappypath-analara)

**Comment by Ana-Lara** [comment]
> The nick name on Trello card is not the same as nick name on PR. Also please provide labels. And please change "PR name" on card to test name Screenshot_20221115_014613_Chrome

Hi Irina, I've updated my Trello cards and changed my PR Name, but not sure which labels I should provide. Could you, please, clarify which labels you mean? I'm confused a little bit. Thank you!

**Review by ArinaJur — APPROVED** [review]

**Pull request merged**
